# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='station_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12station_data.proto\"@\n\x06Record\x12\x0b\n\x03_id\x18\x01 \x01(\x03\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\"*\n\x11GetLatestResponse\x12\x15\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x07.Record\"+\n\x12GetRecordsResponse\x12\x15\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x07.Record\"\x12\n\x10GetLatestRequest\"o\n\x11GetRecordsRequest\x12%\n\x04name\x18\x01 \x01(\x0e\x32\x17.GetRecordsRequest.Name\x12\r\n\x05limit\x18\x02 \x01(\x05\"$\n\x04Name\x12\x07\n\x03\x41LL\x10\x00\x12\x05\n\x01P\x10\x01\x12\x05\n\x01Q\x10\x02\x12\x05\n\x01V\x10\x03\x32\x83\x01\n\x12StationDataService\x12\x34\n\tGetLatest\x12\x11.GetLatestRequest\x1a\x12.GetLatestResponse\"\x00\x12\x37\n\nGetRecords\x12\x12.GetRecordsRequest\x1a\x13.GetRecordsResponse\"\x00\x62\x06proto3'
)



_GETRECORDSREQUEST_NAME = _descriptor.EnumDescriptor(
  name='Name',
  full_name='GetRecordsRequest.Name',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='P', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Q', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='V', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=272,
  serialized_end=308,
)
_sym_db.RegisterEnumDescriptor(_GETRECORDSREQUEST_NAME)


_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='Record._id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='Record.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Record.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Record.value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=86,
)


_GETLATESTRESPONSE = _descriptor.Descriptor(
  name='GetLatestResponse',
  full_name='GetLatestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GetLatestResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=130,
)


_GETRECORDSRESPONSE = _descriptor.Descriptor(
  name='GetRecordsResponse',
  full_name='GetRecordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GetRecordsResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=175,
)


_GETLATESTREQUEST = _descriptor.Descriptor(
  name='GetLatestRequest',
  full_name='GetLatestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=195,
)


_GETRECORDSREQUEST = _descriptor.Descriptor(
  name='GetRecordsRequest',
  full_name='GetRecordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GetRecordsRequest.name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='GetRecordsRequest.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETRECORDSREQUEST_NAME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=308,
)

_GETLATESTRESPONSE.fields_by_name['data'].message_type = _RECORD
_GETRECORDSRESPONSE.fields_by_name['data'].message_type = _RECORD
_GETRECORDSREQUEST.fields_by_name['name'].enum_type = _GETRECORDSREQUEST_NAME
_GETRECORDSREQUEST_NAME.containing_type = _GETRECORDSREQUEST
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.message_types_by_name['GetLatestResponse'] = _GETLATESTRESPONSE
DESCRIPTOR.message_types_by_name['GetRecordsResponse'] = _GETRECORDSRESPONSE
DESCRIPTOR.message_types_by_name['GetLatestRequest'] = _GETLATESTREQUEST
DESCRIPTOR.message_types_by_name['GetRecordsRequest'] = _GETRECORDSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), {
  'DESCRIPTOR' : _RECORD,
  '__module__' : 'station_data_pb2'
  # @@protoc_insertion_point(class_scope:Record)
  })
_sym_db.RegisterMessage(Record)

GetLatestResponse = _reflection.GeneratedProtocolMessageType('GetLatestResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLATESTRESPONSE,
  '__module__' : 'station_data_pb2'
  # @@protoc_insertion_point(class_scope:GetLatestResponse)
  })
_sym_db.RegisterMessage(GetLatestResponse)

GetRecordsResponse = _reflection.GeneratedProtocolMessageType('GetRecordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRECORDSRESPONSE,
  '__module__' : 'station_data_pb2'
  # @@protoc_insertion_point(class_scope:GetRecordsResponse)
  })
_sym_db.RegisterMessage(GetRecordsResponse)

GetLatestRequest = _reflection.GeneratedProtocolMessageType('GetLatestRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLATESTREQUEST,
  '__module__' : 'station_data_pb2'
  # @@protoc_insertion_point(class_scope:GetLatestRequest)
  })
_sym_db.RegisterMessage(GetLatestRequest)

GetRecordsRequest = _reflection.GeneratedProtocolMessageType('GetRecordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRECORDSREQUEST,
  '__module__' : 'station_data_pb2'
  # @@protoc_insertion_point(class_scope:GetRecordsRequest)
  })
_sym_db.RegisterMessage(GetRecordsRequest)



_STATIONDATASERVICE = _descriptor.ServiceDescriptor(
  name='StationDataService',
  full_name='StationDataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=311,
  serialized_end=442,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLatest',
    full_name='StationDataService.GetLatest',
    index=0,
    containing_service=None,
    input_type=_GETLATESTREQUEST,
    output_type=_GETLATESTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRecords',
    full_name='StationDataService.GetRecords',
    index=1,
    containing_service=None,
    input_type=_GETRECORDSREQUEST,
    output_type=_GETRECORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATIONDATASERVICE)

DESCRIPTOR.services_by_name['StationDataService'] = _STATIONDATASERVICE

# @@protoc_insertion_point(module_scope)
